require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - lib/generators/onesie/templates/migration.rb

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ClassStructure:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 100
  IgnoredPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*.rake'
    - 'Rakefile'
    - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Max: 2
